services:
  client:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    environment:
      - SERVER_PORT= 8181
    develop:
      watch:
        - path: ./src
          action: rebuild
          target: /app/src