services:
  client:
    image: client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    environment:
      - SERVER_PORT= 8181
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/src